app/models.py
from app import db
from datetime import datetime
import re



def slugify(text):
	"Задача: взять строку и заменить все не используемые символы в адресной строке на симовол - "
	pattern = r'[^\w+]'
	return re.sub(pattern, '-', text)


posts_tags = db.Table('posts_tags',
			 db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
			 db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
			 )


class Post(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	title = db.Column(db.String(140))
	slug = db.Column(db.String(140), unique=True)
	body = db.Column(db.String(1000))
	created = db.Column(db.DateTime, default=datetime.now())
	tags = db.relationship('Tag',
							secondary=posts_tags,
							backref=db.backref('posts', lazy='dynamic')
								)

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.slug = slugify(self.title)
		

class Tag(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	title = db.Column(db.String(30))
	slug = db.Column(db.String(30), unique=True)
	created = db.Column(db.DateTime, default=datetime.now())

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.slug = slugify(self.title)

app/app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy

# migrate
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

app = Flask(__name__)
app.config.from_object(Configuration)

# data base
db = SQLAlchemy(app)

# migrate
migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

app/blog/blueprint.py
from flask import Blueprint, render_template
from models import Post, Tag

blog = Blueprint('blog', __name__, template_folder='templates')


@blog.route('/')
def main_blog():
	return render_template('blog/main_blog.html')


@blog.route('/some_post')
def some_post():
	return 'Some post'

@blog.route('/<slug>')
def post_show(slug):
	post = Post.query.filter(Post.slug==slug).first()
	return render_template('blog/post_show.html', post=post)

@blog.route('/all_posts')
def all_posts():
	posts = Post.query.all()
	return render_template('blog/all_posts.html', posts=posts)

# @blog.route('/check_tag')
# def check_tag():
# 	tag = Tag.query.first()
# 	post = Post.query.first()
# 	test = Test2.query.first()
# 	return render_template('blog/check_tag.html', tag=tag, post=post, test=test)

app/main.py
from app import app
import view
from blog.blueprint import blog

app.register_blueprint(blog, url_prefix='/blog')

if __name__ == '__main__':
	app.run()

app/blog/templates/blog/all_posts.html
{% extends 'base.html' %}


{% block title %}
	Все посты
{% endblock %}


{% block content_title %}
	Список постов:
{% endblock %}


{% block content %}
	
	{% for post in posts %}
		<div>
		<a href="{{ url_for('blog.post_show', slug=post.slug) }}">{{ post.title }}</a>
		</div>
	{% endfor %}

{% endblock %}

app/blog/templates/blog/check_tag.html
{% extends 'base.html' %}


{% block title %}
	{{ tag.title }}
	{{ post.title }}
	{{ test.title }}
{% endblock %}


{% block content_title %}
	{{ tag.title }}
	{{ post.title }}
	{{ test.title }}
{% endblock %}


{% block content %}
	{{ tag.title }}
	{{ post.body }}
	{{ test.body }}
{% endblock %}

app/blog/templates/blog/main_blog.html
{% extends "base.html" %}


{% block title %}
	Title main block
{% endblock %}


{% block content_title %}
	Title:
{% endblock %}


{% block content %}
	Block content
{% endblock %}

app/blog/templates/blog/post_show.html
{% extends 'base.html' %}


{% block title %}

	{{ post.title }}

{% endblock %}


{% block content_title %}

	{{ post.title }}

{% endblock %}


{% block content %}

	{{ post.body }}

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>



<head>
	<title>
		{% block title %}

		{% endblock %} |MyBlog
	</title>
</head>



<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		<a class="navbar-brand" href="{{ url_for('index') }}">Home</a> <!--Мои проекты - приложения и мини игрушки которые я сделал в книге доусона -->
		<img src="\static\images\monk.jpg" width="40" height="40">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>


		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="{{ url_for('blog.all_posts') }}">Посты<span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#"></a>
				</li>

				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Выпадающий список</a> <!--Разобраться как настроить выпадающий список -->
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="https://flask-russian-docs.readthedocs.io/ru/latest/quickstart.html#id2">Action</a>
						<a class="dropdown-item" href="#">Another action</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="#">Something else here</a>
					</div>
				</li>

				<li class="nav-item">
					<a class="nav-link disabled" href="#">Disabled</a> <!--Пробить функционал этой кнопки -->
				</li>
			</ul>


			<form class="form-inline my-2 my-lg-0">
				<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
				<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
			</form>
		</div>
	</nav>


	<h1>
		{% block content_title %}

		{% endblock %}
	</h1>
	<!--img src='/static/images/monk.jpg'-->

	{% block content %}

	{% endblock %}


</body>
</html>

app/templates/index.html
{% extends "base.html" %}



{% block title %}
	Hello - Page
{% endblock %}



{% block content_title %}
	My first post
{% endblock %}



{% block content %}
	About some various stranges
{% endblock %}